name: Deploy via Git Pull

on:
  push:
    branches:
      - main  # change if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH and deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/app
            git pull origin main
            source venv/bin/activate
            pkill -f "python app.py" || true
            nohup python app.py &
